### PR TITLE
avoid recreating nested object for every run

### PR DESCRIPTION
**Pull request by threepointone**
This helps trigger caching (as it does on all the other tests)

### CODE REVIEW

**Comment by rtsao** [comment]
I think this change probably ought be replicated across all other cases to ensure consistency

**Comment by threepointone** [comment]
Good point, updated the PR for every lib.

**Comment by PhiLhoSoft** [comment]
I did that already in my complex-test-case PR... 😄 
Except in the complex-test because the inline-vendor-prefixer I had to use for some libraries changes the style that has to be re-created each time (not sure if cloning it would be faster anyway).

**Comment by PepijnSenders** [comment]
So what I understand from @PhiLhoSoft, this PR is now redundant?

**Comment by PhiLhoSoft** [comment]
Yes.

**Pull request closed without merging**
