### PR TITLE
Add free-style library to benchmark

### PR DESCRIPTION
**Pull request by stevenbenisek**
Added benchmarks for the [Free-Style](https://github.com/blakeembrey/free-style) library.
**Note:** I didn't update the README yet. Should I?

```
Running simple test.
aphrodite length 470
jss length 447
jss-without-preset length 443
glamor length 428
cxs length 400
cxs-optimized length 445
free-style length 374
  7 tests completed.

  aphrodite          x  7,642 ops/sec ±4.65% (72 runs sampled)
  jss                x 13,941 ops/sec ±3.72% (76 runs sampled)
  jss-without-preset x 21,122 ops/sec ±3.22% (81 runs sampled)
  glamor             x  7,656 ops/sec ±1.41% (85 runs sampled)
  cxs                x 15,747 ops/sec ±3.43% (79 runs sampled)
  cxs-optimized      x 12,504 ops/sec ±3.38% (79 runs sampled)
  free-style         x 17,517 ops/sec ±2.77% (76 runs sampled)

Fastest is: jss-without-preset
```

```
Running styles overload test.
aphrodite length 3594
jss length 3509
jss-without-preset length 3471
glamor length 3298
cxs length 3022
cxs-optimized length 3063
free-style length 2760
  7 tests completed.

  aphrodite          x 1,168 ops/sec ±1.53% (78 runs sampled)
  jss                x 2,137 ops/sec ±1.71% (83 runs sampled)
  jss-without-preset x 2,802 ops/sec ±2.28% (77 runs sampled)
  glamor             x   807 ops/sec ±2.46% (73 runs sampled)
  cxs                x 1,595 ops/sec ±2.85% (76 runs sampled)
  cxs-optimized      x 1,450 ops/sec ±2.88% (75 runs sampled)
  free-style         x 1,973 ops/sec ±1.77% (86 runs sampled)

Fastest is: jss-without-preset
```

```
Running classes overload test.
aphrodite length 3044
jss length 3085
jss-without-preset length 3085
glamor length 1932
cxs length 1943
cxs-optimized length 1943
free-style length 1805
  7 tests completed.

  aphrodite          x 1,667 ops/sec ±1.58% (81 runs sampled)
  jss                x 2,815 ops/sec ±2.63% (79 runs sampled)
  jss-without-preset x 3,890 ops/sec ±1.82% (85 runs sampled)
  glamor             x 2,809 ops/sec ±1.85% (81 runs sampled)
  cxs                x 2,345 ops/sec ±2.17% (83 runs sampled)
  cxs-optimized      x 2,024 ops/sec ±1.79% (84 runs sampled)
  free-style         x 2,027 ops/sec ±2.31% (79 runs sampled)

Fastest is: jss-without-preset
```

```
Size free-style 8.023KB
Size glamor 32.306KB
Size cxs 9.366KB
Size cxs-optimized 12.268KB
Size jss-without-preset 24.654KB
Size jss 37.185KB
Size aphrodite 19.711KB
```

### CODE REVIEW

**Comment by PepijnSenders** [comment]
Hey @stevenbenisek, I can smack myself in the head for forgetting free-style, this was actually one of the libs I started one of my projects with. I will integrate this first thing tomorrow, you may add the results to the README as well, thanks!

**Comment by PepijnSenders** [comment]
Hey @stevenbenisek, another contributor @rtsao did a Pull Request that changes the flow per test a little bit, you can see it here: https://github.com/hellofresh/css-in-js-perf-tests/pull/7. You should use the new render method and also the way to generate styles changed.

**Comment by stevenbenisek** [comment]
@PepijnSenders Pull Request updated to reflect changes in #7. I'll create a new Pull Request to add the Free-Style results when #11 gets merged

**Comment by PepijnSenders** [comment]
Hey @stevenbenisek, sorry to see that this PR got a bit out-dated, could you please update again? 😄

**Comment by PepijnSenders** [comment]
Closing because it was already done in another PR https://github.com/hellofresh/css-in-js-perf-tests/pull/17.

**Pull request closed without merging**
