### PR TITLE
Added another test: Nested style objects

### PR DESCRIPTION
**Pull request by rofrischmann**
I added another test to check another common real-world case: pseudo classes and media queries. If that fits fine, feel free to merge.

### CODE REVIEW

**Comment by PepijnSenders** [comment]
Hey @rofrischmann, looks good, but can you merge `master` on this branch?

**Comment by rofrischmann** [comment]
ofc, gimme a sec :P

**Comment by rofrischmann** [comment]
Should be up-to-date now :P

**Comment by PepijnSenders** [comment]
LGTM 👍

**Pull request merged**
